name: simple_svg
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/simmone/dart_simple_svg

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  complex: ^0.8.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
